### ISSUE TITLE
Error Importing Non-blank Client

### ISSUE THREAD

**Issue by HawaiianSpork** [yieldr/terraform-provider-auth0#39]
Terraform Crashes when importing a non-blank client.  It worked fine when importing a blank client.

```
» terraform import module.foo_login.auth0_client.foo_login "ZmZ6Rao2EzsDXOY5ptwz6irH3lgq8G6n"
module.foo_login.auth0_client.foo_login: Importing from ID "ZmZ6Rao2EzsDXOY5ptwz6irH3lgq8G6n"...
module.foo_login.auth0_client.foo_login: Import complete!
  Imported auth0_client (ID: ZmZ6Rao2EzsDXOY5ptwz6irH3lgq8G6n)
module.foo_login.auth0_client.foo_login: Refreshing state... (ID: ZmZ6Rao2EzsDXOY5ptwz6irH3lgq8G6n)

Error: module.foo_login.auth0_client.foo_login (import id: ZmZ6Rao2EzsDXOY5ptwz6irH3lgq8G6n): 1 error(s) occurred:

* import module.foo_login.auth0_client.foo_login result: ZmZ6Rao2EzsDXOY5ptwz6irH3lgq8G6n: auth0_client.foo_login: unexpected EOF


panic: interface conversion: interface {} is map[string]interface {}, not *schema.Set
2018-08-20T06:03:03.312-0500 [DEBUG] plugin.terraform-provider-auth0:
2018-08-20T06:03:03.312-0500 [DEBUG] plugin.terraform-provider-auth0: goroutine 59 [running]:
2018-08-20T06:03:03.312-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*MapFieldWriter).setSet(0xc42026e340, 0xc42022eac0, 0x1, 0x1, 0x18de5a0, 0xc4206f0000, 0xc4203d0780, 0x1, 0x6)
2018-08-20T06:03:03.312-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/field_writer_map.go:343 +0xa63
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*MapFieldWriter).set(0xc42026e340, 0xc42022eac0, 0x1, 0x1, 0x18de5a0, 0xc4206f0000, 0x1, 0x1)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/field_writer_map.go:107 +0x2ac
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*MapFieldWriter).WriteField(0xc42026e340, 0xc42022eac0, 0x1, 0x1, 0x18de5a0, 0xc4206f0000, 0x0, 0x0)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/field_writer_map.go:89 +0x46a
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).Set(0xc420396310, 0x1a01ade, 0x6, 0x18de5a0, 0xc4206f0000, 0x1af22e0, 0xc42022eab0)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:189 +0x12b
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/auth0.readClient(0xc420396310, 0x1982bc0, 0xc42044c000, 0xc420396310, 0x0)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/auth0/resource_auth0_client.go:263 +0x8d0
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4203c28c0, 0xc4202661e0, 0x1982bc0, 0xc42044c000, 0xc4203c47d8, 0x10bd001, 0x185cb40)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x167
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4203c3180, 0xc420266190, 0xc4202661e0, 0x18, 0x18, 0xc4202643a0)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42000c600, 0xc4202780e0, 0xc420278290, 0x0, 0x0)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/Users/mmaletich/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: reflect.Value.call(0xc420094a80, 0xc42000e440, 0x13, 0x1a0000b, 0x4, 0xc420065f18, 0x3, 0x3, 0xc4203b8ac0, 0x0, ...)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:447 +0x969
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: reflect.Value.Call(0xc420094a80, 0xc42000e440, 0x13, 0xc42037e718, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:308 +0xa4
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: net/rpc.(*service).call(0xc420082900, 0xc42034a1e0, 0xc4200364d0, 0xc4200364e0, 0xc4203ba680, 0xc4203ec560, 0x185cb00, 0xc4202780e0, 0x16, 0x185cb40, ...)
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/usr/local/Cellar/go/1.10.3/libexec/src/net/rpc/server.go:384 +0x14e
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: created by net/rpc.(*Server).ServeCodec
2018-08-20T06:03:03.313-0500 [DEBUG] plugin.terraform-provider-auth0: 	/usr/local/Cellar/go/1.10.3/libexec/src/net/rpc/server.go:480 +0x43a
2018/08/20 06:03:03 [ERROR] root.foo_login: eval: *terraform.EvalRefresh, err: auth0_client.foo_login: unexpected EOF
2018/08/20 06:03:03 [ERROR] root.foo_login: eval: *terraform.EvalSequence, err: auth0_client.foo_login: unexpected EOF
2018/08/20 06:03:03 [TRACE] [walkImport] Exiting eval tree: import module.foo_login.auth0_client.foo_login result: ZmZ6Rao2EzsDXOY5ptwz6irH3lgq8G6n
2018/08/20 06:03:03 [TRACE] dag/walk: upstream errored, not walking "provider.auth0 (close)"
2018/08/20 06:03:03 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-08-20T06:03:03.318-0500 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-08-20T06:03:03.318-0500 [DEBUG] plugin: plugin process exited: path=/Users/mmaletich/.terraform.d/plugins/terraform-provider-auth0



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
------------------------------------------------------------
```

Terraform v0.11.7

**Comment by alexkappa** [comment]
Hi @HawaiianSpork thanks for submitting an issue. Could you clarify what you mean by a blank vs a non-blank client?

**Comment by HawaiianSpork** [comment]
oh, sorry. When I say blank.  I mean I create a client in the Auth0 UI and don't do anything to it.  I'll see if I can figure out what configuration option is not being imported.

**Comment by alexkappa** [comment]
@HawaiianSpork could you please tests against the latest release and let me know if the problem persists?

**Comment by alexkappa** [comment]
Closing due to inactivity, the problem should be solved. If now, feel free to re-open
