### ISSUE TITLE
Problem with creating client

### ISSUE THREAD

**Issue by robertstettner** [yieldr/terraform-provider-auth0#74]
Hi,

I am using the latest v0.1.12, and I am having an issue creating an Auth0 Client Application, here is my stanza:

```
resource "auth0_client" "application" {
  name            = "My Blog"
  description     = "My Blog"
  app_type        = "regular_web"
  is_first_party  = true
  oidc_conformant = true
  callbacks       = ["https://${aws_route53_record.main.fqdn}/oauth2/idpresponse"]
  allowed_origins = ["https://${aws_route53_record.main.fqdn}"]
  web_origins     = ["https://${aws_route53_record.main.fqdn}"]
  grant_types     = ["authorization_code", "implicit", "refresh_token"]

  custom_login_page_on = true
}
```

And here is the stack trace:
```
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: panic: runtime error: invalid memory address or nil pointer dereference
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1808f51]
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: goroutine 10 [running]:
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management.(*Management).request(0xc000394210, 0x1a18111, 0x4, 0xc000400000, 0x141, 0x1900200, 0xc0003f8000, 0x0, 0x0)
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management/management.go:136 +0xd1
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management.(*Management).post(0xc000394210, 0xc000400000, 0x141, 0x1900200, 0xc0003f8000, 0x141, 0xc00009c9c8)
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management/management.go:172 +0x68
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management.(*ClientManager).Create(0xc00032a4b8, 0xc0003f8000, 0x17bb1ac, 0xc0002c6f20)
2019-01-18T13:59:04.334Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management/client.go:114 +0xa1
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/auth0.createClient(0xc0003b2380, 0x19a1f40, 0xc000394210, 0x24, 0x228dce0)
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/auth0/resource_auth0_client.go:447 +0x5f
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000354a80, 0xc0000ad4a0, 0xc0002c6f20, 0x19a1f40, 0xc000394210, 0x100b601, 0xc00009cb80, 0x10bd81c)
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000355110, 0xc0000ad450, 0xc0000ad4a0, 0xc0002c6f20, 0xc000088000, 0x18, 0x2600000)
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc000132560, 0xc0002c6b00, 0xc0003b7740, 0x0, 0x0)
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: reflect.Value.call(0xc00031c600, 0xc00032a080, 0x13, 0x1a17ffd, 0x4, 0xc00009cf18, 0x3, 0x3, 0xc0000460c0, 0x0, ...)
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/reflect/value.go:447 +0x454
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: reflect.Value.Call(0xc00031c600, 0xc00032a080, 0x13, 0xc00006af18, 0x3, 0x3, 0x0, 0x0, 0x0)
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: net/rpc.(*service).call(0xc000300280, 0xc000328140, 0xc0003021f0, 0xc000302200, 0xc00034c200, 0xc000324a20, 0x1889040, 0xc0002c6b00, 0x16, 0x1889080, ...)
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: created by net/rpc.(*Server).ServeCodec
2019-01-18T13:59:04.335Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/net/rpc/server.go:481 +0x47e
```

Could you please help?

**Comment by robertstettner** [comment]
Same output as above, nothing new.

```
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: panic: runtime error: invalid memory address or nil pointer dereference
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1808f51]
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: goroutine 51 [running]:
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management.(*Management).request(0xc00034c2c0, 0x1a18111, 0x4, 0xc000468000, 0x141, 0x1900200, 0xc000372600, 0x0, 0x0)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management/management.go:136 +0xd1
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management.(*Management).post(0xc00034c2c0, 0xc000468000, 0x141, 0x1900200, 0xc000372600, 0x141, 0xc0003f69c8)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management/management.go:172 +0x68
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management.(*ClientManager).Create(0xc00013a470, 0xc000372600, 0x17bb1ac, 0xc0003d6ce0)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/yieldr/go-auth0/management/client.go:114 +0xa1
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/auth0.createClient(0xc0003e6380, 0x19a1f40, 0xc00034c2c0, 0x24, 0x228dce0)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/auth0/resource_auth0_client.go:447 +0x5f
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000388850, 0xc000402140, 0xc0003d6ce0, 0x19a1f40, 0xc00034c2c0, 0x100b601, 0xc0003f6b80, 0x10bd81c)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000388ee0, 0xc0004020f0, 0xc000402140, 0xc0003d6ce0, 0xc000368000, 0x18, 0x2601440)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc000135b40, 0xc0003d68c0, 0xc0003e1930, 0x0, 0x0)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/go/src/github.com/yieldr/terraform-provider-auth0/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: reflect.Value.call(0xc000126840, 0xc00013a038, 0x13, 0x1a17ffd, 0x4, 0xc0003f6f18, 0x3, 0x3, 0xc000384040, 0x0, ...)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/reflect/value.go:447 +0x454
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: reflect.Value.Call(0xc000126840, 0xc00013a038, 0x13, 0xc000334f18, 0x3, 0x3, 0x0, 0x0, 0x0)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: net/rpc.(*service).call(0xc00014a140, 0xc00033e1e0, 0xc00014c178, 0xc00014c1a0, 0xc00014e300, 0xc00013c9e0, 0x1889040, 0xc0003d68c0, 0x16, 0x1889080, ...)
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: created by net/rpc.(*Server).ServeCodec
2019-01-21T14:52:55.328Z [DEBUG] plugin.terraform-provider-auth0_v0.1.12: 	/usr/local/go/src/net/rpc/server.go:481 +0x47e
```

**Comment by robertstettner** [comment]
Sorry my mistake, I was putting in the client secret into the domain parameter of the auth0 provider. Stupid me.

So request was failing because it wasn't a valid domain. Would've been nice to have a friendly error message.

**Comment by alexkappa** [comment]
Yes, that confirms my suspicion :) 

Indeed a proper error message should be returned in this case. I'll keep this ticket open then, but rename it so we can keep track of it.
